### ISSUE TITLE
key milestone: Be able to turn a knob into an input!

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/msvr#3]
Graham mentioned that in the review videos of hardware MS, he often hears the phrase “oh I wish they put a modulation/cv input here”.  so, we should have a reasonable way to instantly add a cv input to a knob.

questions:

how does the cv get scaled? should it default to be scaled by the range of the knob? For now, this is what I will do. 

should we be exchanging a knob for an input, or should an input be added beside the knob?

What if adding an input to a knob resulted in a knob with an input on top, i.e. you can plug a cable directly into the knob (would this be complicated for collision detection?)

Should the signal affect/be affected by the knob? i.e. should the knob attenuvert the cv signal (as in the case of the +/- trim pots for cv inputs of the Mutable Instruments Rings module)

This action, how does it work with saved modules?

**Comment by michaelpalumbo** [comment]
tracking on branch [knob2cv](https://github.com/worldmaking/msvr/tree/knob2cv) as of 0160e968521d5ed0157874d339079b7896bbd6f3

**Comment by Zodsmar** [comment]
So I am trying to understand what you mean by " instantly add a cv input to a knob ". From what I gather you want the ability to convert any inlet into a knob for easier control? If so we could add almost like a donut around the inlet. Have a small gap between the inlet and the donut shape which would then be the knob. So still for collisions and selection, you can interact with the inlet but around it, you can grab the donut which can be turned. Am I understanding this correctly?

**Comment by Georgeyo** [comment]
Perhaps we can have mini inlets for each knob in one of the corners of the grid space for that knob (since the knobs and other pieces of a module are all positioned in a grid), this would prevent having the extra inlets mess with the grid spacing for the other parts of the module. Additionally, pointing a jack inlet at the knob itself or the mini inlet of that knob will count for intersecting with that knob as an inlet, and either way the jack inlet will snap to the mini inlet of that knob (whether or not the intersection is with the knob itself or with the mini inlet)

**Comment by Georgeyo** [comment]
![image](https://user-images.githubusercontent.com/33497047/60835027-2505a400-a190-11e9-8359-4dfe004124bd.png)

For example: Above is a blue panel with three magenta knobs and one green mini inlet for each knob. the black lines represent the grid space for each knob (This grid is not visible, but has been drawn in for explanatory reasons). Each knob would get it's own inlet whose positions would all be thew same relative to their respective knob's gridspace.

**Comment by michaelpalumbo** [comment]
@Zodsmar 
> From what I gather you want the ability to convert any inlet into a knob for easier control?

Actually the opposite! Perhaps a useful way to think about control voltage modulation is the concept of automation. So if I have a knob on module that I'm using often, or perhaps I can't turn it fast enough, or whatever... being able to immediately add cv in to a knob is really useful. 

@Georgeyo that's a compelling solution. I'm trying to think of a case in which *not* having a cv-input assigned to a knob-parameter would be more desirable, and all I can think of at the moment is the module layout. Perhaps having all as a default is potentially too cluttered? Worth a try though! 

However, I maintain that being able to rapidly add a cv input to a lonely knob is really useful. I do also think that there may be cases where adding a secondary cv to a control parameter is also useful, see the Befaco Rampage module (one of my favourites, super useful):
Both *Rise* and *Fall* sliders have a CV input, BUT there is also a third CV input which modulates both individual CVs. At [2:26 in this video](https://www.youtube.com/watch?v=drDfZAkVi4k), he demonstrates the three cv inputs.

**Comment by grrrwaaa** [comment]
Yes the key concept is this: anything you can tweak by hand, you ought to also be able to automatically tweak by plugging in a signal.  As if the patch cord became a hand that turns the knob (or pushes the button etc.). It is one of those simple but powerfully generic and constructive ideas. 

In terms of implementation, there's a few obvious modes in how this would be interpreted:
1. the incoming signal *overrides* the current knob position, setting its value directly. 
2. the incoming signal *adds* to the current knob position, like adding a wobble/vibrato for example.
3. the incoming signal *multiples* with the current knob position, so that the knob effectively attenuates the modulation. 
(Furthermore, you might want to take into consideration whether a signal and/or knob is signed or positive only, and what kind of range, and linear/exponential, etc. etc.)

In a way, mode (1) is the most generic, because you can emulate the others by adding another operator module (just as you could add modules to achieve what is in the video above) -- this could be part of the inner workings of a module too. But it might be that these kinds of behaviours are so commonly used that we would want a quicker way of creating it (and that conceptually in many cases they belong outside the module). 

Having different CV spots around a knob to do so might be a really neat UI for building those variations, whereas having a CV right in the middle of the knob itself seems to be more logical for mode (1), as it is the one in which the signal is most directly "turning the knob".

**Comment by grrrwaaa** [comment]
Shorter answer: implement mode 1 first, and don't let other options slow that down! :-)

**Comment by Zodsmar** [comment]
Awesome! I understand better what needs to be done. On the Javascript side this shouldn't be too hard we have the value code already set up and it pulls directly from the Value that comes in from the OT. I guess the cables will need to hold a value maybe? And when it gets plugged in just do a simple check for a value and if it exists to override the knob value.

**Comment by grrrwaaa** [comment]
Actually this also relates to #7 -- if a knob has a signal plugged in, it needs to display the dynamic value, just like an LED. The cable itself won't hold a value, the knob will need receive snapshots directly from Max. 

For any modes other than option (1) (overriding the knob), we'd have to visually distinguish between the knob value (as determined by a human interacting with it, and stored in the graph) and the dynamic value (as determined by the signal being generated by the combination of the knob and input signals, and received as a snapshot from Max). E.g like a knob with a circular LED around it [https://images.app.goo.gl/bJKHiGkhpXpsr8yy6](perhaps like this).

**Comment by grrrwaaa** [comment]
(Interestingly it seems that knob and input and LED are starting to look like three variations of the same thing...)

**Comment by Zodsmar** [comment]
Added ability to add jacks to knobs. OT side needs to be updated to support this behavior
